### ISSUE TITLE
Support for easy-rsa version 3

### ISSUE THREAD

**Issue by ivanfetch** [voxpupuli/puppet-openvpn#216]
This module should detect version 3 of easy-rsa, and use the updated vars file and no longer source the vars file before running easyrsa.

FreeBSD uses easy-rsa 3 as a dependency to OpenVPN.

**Comment by TeunRoefs** [comment]
Any progress with this? Seems the epel-release has been updated with easy-rsa 3.0.3 instead of 2.0 and this module will now always fail on Red Hat Enterprise Linux 7.4.

**Comment by bastelfreak** [comment]
@TeunRoefs are you able to provide a PR for this?

**Comment by TeunRoefs** [comment]
@bastelfreak I thought it would be as easy as changing 2.0 to 3.0.3 wherever applicable, but I keep getting the following error when running Puppet.

`./vars: line 29: /etc/openvpn/aws/easy-rsa/whichopensslcnf: No such file or directory`

**Comment by monkey670** [comment]
For what I was doing the files that need changing are the params.pp to use version 3, the template vars file for the newer variables and the ca.pp to use the newer commands whilst removing the ./vars call. I've managed to stand up a working openvpn server with these changes on RHEL 7.4 using easy-rsa 3.0.3.

I might be wrong but is this the variable EASYRSA_REQ_CN="ChangeMe" you can use to set the Common Name in the ./vars file or at command runtime?

**Comment by ElvenSpellmaker** [comment]
@jameskirsop You can `echo` a Common Name and pipe it in, the newline from echo will act like you've hit enter.

So, `echo foo | ./easyrsa build-ca nopass` will work.
When I had a brief look at this I couldn't work out what CN was needed here...

**Comment by ElvenSpellmaker** [comment]
As mentioned in #269, Epel has now replaced `easy-rsa` with version 3.x and so this module is now broken for anyone using CentOS (at least EL7).

**Comment by jameskirsop** [comment]
After a fair bit of hacking around I've got something that creates working server and client configs, but the changes are pretty dirty and will need cleanup before I commit them to my fork and create a PR. I'll try and do this over the next week or so.

I ended up adding a clause specifically for CentOS 7 that uses a different params file so that anything using the pre 3.x easy-rsa still works OK.

I'm not able to get the client to auto deploy config successfully though... but that's probably outside the scope of this thread.

**Comment by barrypitman** [comment]
I was able to work around this by manually uninstalling easy-rsa 3 and installing easy-rsa 2 [from RPM](http://rpm.pbone.net/index.php3/stat/4/idpl/40946036/dir/redhat_el_7/com/easy-rsa-2.2.2-1.el7.noarch.rpm.html)

**Comment by ElvenSpellmaker** [comment]
Odd because I can't find `easy-rsa`2.x in the epel repo any more...

**Comment by TeunRoefs** [comment]
@barrypitman That was also my solution for the time being, however the EPEL does not contain easy-rsa anymore. I was lucky enough to retrieve it from another server. See my attachment for all the files in the 2.0 folder.

[easy-rsa.zip](https://github.com/voxpupuli/puppet-openvpn/files/1818801/easy-rsa.zip)

**Comment by jameskirsop** [comment]
I've got a branch over at [my fork which has changes](https://github.com/jameskirsop/puppet-openvpn/tree/easy-rsa-3.0) that fix CA certificate generation under easy-rsa 3.0 on CentOS7. It seems like I can't do a PR for this change though due to insufficient permissions.

I've got some other changes for the server template and client manifest, but I need to clean them up a little more before committing them.

**Comment by ElvenSpellmaker** [comment]
Hey @jameskirsop, I thought I'd have a brief look at the diff between yours and the master and I found this line here: https://github.com/voxpupuli/puppet-openvpn/compare/master...jameskirsop:easy-rsa-3.0?expand=1#diff-b386e10e7f4de7981ca1d52c90456a0dR257

Is it meant to have `&& &&` like that? Won't that break?

**Comment by jameskirsop** [comment]
Whoops, not at all! I must have done something between my last test and
that commit.

I've just committed a fix that corrects that typo. Good pickup!!

**Comment by jsnod** [comment]
Yep, this is broken in CentOS 6 now too.

**Comment by NoodlesNZ** [comment]
Have added #278 to address this

**Comment by Dan33l** [comment]
Since PR #292 is merged, this bug should be considered as closed.

Thank you @NoodlesNZ for the work proposed with PR #278 used as a basis.
