### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by tarjei** [voxpupuli/puppet-openvpn#323]
Hi, any chance of releasing a new version with support for Ubuntu 18.04 or should I just use master?

**Comment by Dan33l** [comment]
Hi @tarjei,
Because we have a backward incompatible PR #305 , this will be a new major version.
We have also in the pipe some others PR #308 and #309 also backward incompatibles. 
And we try to change the major version in a frequency that is not too high.

But i understand that Ubuntu 18.04 is expected. Lets try to move forward about the two others PR.
Thank you for your question.

**Comment by tarjei** [comment]
Thank you for a great module and a very quick answer :)

I'm closing this for now.
